{
    "name": """Multi categories in POS""",
    "summary": """Specify as many categories for a product as you need""",
    "category": "Point of Sale",
    "version": "11.0.1.0.1",
    "images": [],
    "author": "IT-Projects LLC, Pavel Romanchenko",
    "support": "apps@itpp.dev",
    "website": "https://itpp.dev",
    "license": "AGPL-3",
    "price": 15.00,
    "currency": "EUR",
    "depends": ["point_of_sale"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["template.xml", "view.xml"],
    "demo": [],
    "installable": True,
    "auto_install": False,
}
