{
    "name": """POS restaurant base""",
    "summary": """Technical module in POS""",
    "category": "Point of Sale",
    # "live_test_URL": "",
    "images": ["images/pos_restaurant_base.jpg"],
    "version": "13.0.2.0.4",
    "application": False,
    "author": "IT-Projects LLC, Dinar Gabbasov",
    "support": "pos@it-projects.info",
    "website": "https://apps.odoo.com/apps/modules/13.0/pos_restaurant_base/",
    "license": "Other OSI approved licence",  # MIT
    "depends": ["pos_restaurant"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/template.xml"],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "auto_install": False,
    "installable": True,
}
