# License MIT (https://opensource.org/licenses/MIT).
from . import http
from . import pos_config
from . import pos_order
from . import pos_restaurant
from . import pos_wechat_miniprogram
from . import product
from . import res_company
from . import res_users
from . import wechat_order
from . import pos_multi_session_models
from . import ir_attachment
