{
    "name": """POS: Refunds analysis""",
    "summary": """Waiter specifies refund reason to avoid serving mistakes in future.""",
    "category": "Point of Sale",
    "images": ["images/pos_order_cancel_restaurant.png"],
    "version": "11.0.1.5.1",
    "application": False,
    "author": "IT-Projects LLC, Dinar Gabbasov",
    "support": "apps@itpp.dev",
    "website": "https://twitter.com/gabbasov_dinar",
    "license": "Other OSI approved licence",  # MIT
    "price": 50.00,
    "currency": "EUR",
    "depends": ["pos_order_cancel", "pos_restaurant_base"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/template.xml", "views/views.xml"],
    "qweb": ["static/src/xml/cancel_order.xml"],
    "demo": ["data/pos_cancelled_reason_demo.xml"],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "auto_install": False,
    "installable": True,
}
